import type { Metadata } from "next";
import "./globals.css";
import "atropos/css";
import Navbar from "@/components/templates/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/templates/footer";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BYekan = localFont({
  src: "../../public/fonts/BYekan/BYekan+ Bold.ttf",
  variable: "--font-BYekan",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="fa" dir="rtl" className={`${BYekan.variable}`}>
      <body>
        <Navbar />
        {children}
        <Footer />

        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
